<?php namespace ProcessWire;

class site-simple-blog-multilanguage implements Module{
  public static function getModuleInfo() {
    return array(
      'title' => 'Simple Multilingual Blog Profile for ProcessWire',
      'summary' => 'Site profile for ProcessWire offers a simple, multilingual and responsive blog which doesn't require any third-party modules.',
      'author' => 'tcnet',
      'version' => 1);
  }
}